### ISSUE TITLE
Fails to plot larger data in Jupyter notebooks

### ISSUE THREAD

**Issue by wentasah** [mbaz/Gaston.jl#103] opened 2019-04-02 07:17 UTC
When I write the following in a Jupyter notebook, I see the graph normally:
```julia
using Gaston
plot(rand(4600))
```
When I increase the size of data (e.g. `rand(4650)`), the plot no longer appears as well as all later plots, no matter how large their data are. Plotting starts working again only after restarting the kernel.

**Comment by mbaz** [comment] 2019-04-02 12:14
This is probably caused by a timeout, since the resulting SVG plot is likely very large and communicating via stdin and stdout is slow. In any case, Gaston should be informing you of the timeout and recovering, instead of silently failing. I'll fix this in the next release.

On a more philosophical note, there's little point in plotting more data than you have horizontal pixels in your screen, since you can't zoom in anyway.

**Comment by wentasah** [comment] 2019-04-02 12:24
Thanks for promising the warning. Would it help to make it configurable to send PNG instead of SVG?

Regarding your note - there are many use cases, where it is beneficial to plot more data than screen resolution: 

1. If I have a noisy signal, I can see approximate amplitude of the noise.
2. I can also have a scatter plot with a lot of points and I'm interested in their density.
3. If the image is SVG, one can export the notebook to html and zoom in the image.

**Comment by mbaz** [comment] 2019-04-02 12:33
Those are good points :)  and of course the user is always right. I hope to have a fix in master in a few days.

**Comment by mbaz** [comment] 2019-04-02 12:39
Regarding support for PNG in addition to SVG, that is an option, my main concern is the increase in maintenance load of two use cases vs one.

Also, the main problem in using stdin and stdout to communicate with gnuplot is that there's no way to know in advance how much data to read. Relying on the stream being empty for some time is not a good solution (that is what Gaston does right now and it fails in your case). With SVG, at least I can look for the closing `</svg>` tag. With PNG, I'm not sure there's a way to know all the data is in.

**Comment by wentasah** [comment] 2019-04-03 07:53
I looked at the Gaston code and tried to investigate the issue more. I think that what's happening here is a deadlock. `ChanStdOut` queue can hold only 10 items. This means that when gnuplot fills this channel and OS kernel's pipe buffer (64 KiB by default on Linux), gnuplot blocks (i.e. waits for space in the pipe buffer) and never executes `printerr "GastonDone"`.

This situation is handled in `llplot()`, but for some reason `error()` messages are not visible in the Jupyter notebook (interestingly, `@error` messages are visible).

Another problematic thing in the current implementation, which makes plotting slow, is the use of increasing sleeps in stdout/err waiting loops. Because of limited size of OS pipe buffers, large data will always be sent from gnuplot to Julia in multiple chunks. In each iteration, Gason waiting loops read one chunk and sleep for increasing amount of time, even if the next chunk of data is (almost) immediately available. In the end, plotting large graphs takes long time not because of pipe slowness, but because of the sleeps.

I think I have a better solution for communication between gnuplot an Julia, so if you don't mind, I'll send a pull request, after cleaning it a bit.

**Comment by mbaz** [comment] 2019-04-08 00:00
@wentasah Thanks for looking at this. I spent some time debugging the problem in the past couple of days and I arrived at the same conclusion; the problem is a deadlock.

I took a quick look at your changes and they look interesting, but I need some time to understand them better. Some things that the final implementation needs to be able to handle (and the reason behind some of the code in Gaston) are the following:

* The host may be slow or running on a slow connection; this is the reason behind increasing the sleep time. One change I have in my local branch is smaller default sleep time and increment, with additional commands to let the user modify them if they need to.

* Recover in the case Gnuplot fails or crashes. That's the reason Gaston gives up if it doesn't see "GastonDone" on stderr after a while.

* Don't start a new plot until the previous plot is finished. A race condition that was present in earlier versions was, a plot command issued right after another could modify the first's data file before gnuplot was finished plotting. This is the reason Gaston waits for "GastonDone" before returning.

**Comment by wentasah** [comment] 2019-04-08 07:42
I think all you points are taken into account by my changes. It should be clear from commit 
2311fc6  that implements `async_reader` and from its tests (see PR #104 thread). Instead of using `sleep()`, `async_reader` uses timeout `Timer`, which runs in parallel with reading of gnuplot output. Therefore, if the output arrives quickly, no `sleep()` delays the execution. If, on the other hand, no new output arrives for longer time (5 seconds), the `Timer` expires and forces plotting to abort on timeout.

Also note, that 5 seconds is not the timeout for the whole figure. It is a timeout for just one chunk of data from gnuplot. So if gnuplot is slow and sends e.g. just one byte every second, you should still receive the whole image without a timeout, but it will take long time.

**Closed** 2019-04-18 18:37 UTC
