### ISSUE TITLE
REPL hanging after a second plot

### ISSUE THREAD

**Issue by my-little-repository** [mbaz/Gaston.jl#39] opened 2015-07-20 20:23 UTC
I just upgraded julia and gaston to latest version today, and I get a weird behavior at the repl (cli or emacs).
The first plot is fine but the repl hangs for ever after a second plot.

      julia> using Gaston      
      julia> set_terminal("x11")
      "x11"      
      julia> plot(sin(-10:0.01:10))
      0      
      julia> plot(sin(-5:0.01:5))
      
The plot occurs (same window) but the REPL does not return. Interrupt gives

        C-c C-cERROR: InterruptException:
       in process_events at ./stream.jl:639
       in wait at ./task.jl:298
       in wait at ./task.jl:225
       in sleep at ./stream.jl:613
       in llplot at /home/mlr/.julia/v0.4/Gaston/src/gaston_midlvl.jl:359
       in plot at /home/mlr/.julia/v0.4/Gaston/src/gaston_hilvl.jl:230

I can replicate the problem with the qt terminal. I don't have wxt installed so I don't know if the problem appears in that case. Subsequent plots hang the repl in the same way.

**Comment by mbaz** [comment] 2015-07-20 20:47
I can't reproduce this, but I have an idea what the reason could be. What
OS are you on? What happens if you comment out lines 356--370 in
gaston_midlvl.jl?

**Comment by my-little-repository** [comment] 2015-07-20 21:32
After commenting lines 356--370 in gaston_midlvl.jl, the problem disappears. The repl returns as expected (cli, emacs, qt, x11). Also I don't have a warning or error when using a non-existing terminal (wxt), the repl returns and of course no graph is displayed.

I am using GNU/Linux 3.16.0-4-amd64 with a  Debian stable Jessie distribution, on a fairly recent HP PC laptop.

**Comment by mbaz** [comment] 2015-07-20 22:50
OK, thanks. Those lines are intended to (1) wait until gnuplot is done
plotting before returning (prevents a rare race condition when issuing two
consecutive plot commands to the same figure in quick succession), and (b)
to capture any output from gnuplot. I introduced this functionality
recently and I haven't tested it with Julia 0.4.

I'll explore this further, but in the meantime, I think it's safe to
proceed with those lines commented. The only consequence is that any
gnuplot output will be inelegantly dumped to your julia repl.

**Comment by mbaz** [comment] 2015-07-21 02:36
I can reproduce this problem on Julia 0.4. I suspect fixing this properly
will need to wait until https://github.com/JuliaLang/julia/issues/11824 is
fixed.

**Comment by mbaz** [comment] 2016-01-19 00:11
Fixed by https://github.com/mbaz/Gaston.jl/commit/6b7b673952f4b8fa5bbbedf88fb10cb0b3db5860

**Closed by mbaz** 2016-01-19 00:11 UTC
