### ISSUE TITLE
Control of the placement of the key (legend)

### ISSUE THREAD

**Issue by PetrKryslUCSD** [mbaz/Gaston.jl#86] opened 2018-05-03 00:55 UTC
I've tried using
```
Gaston.gnuplot_send("set key at 0,0 top left")
```
to control the placement of the key, but no matter when I admit this command it gets ignored. Am I using it right?

Thanks.

Petr

**Comment by mbaz** [comment] 2018-05-03 13:49
It's possible that Gaston is overwriting your `set` command when it creates the plot. Have you tried using the `gpcom` argument to the plot commands? Something like

    plot(1:10, gpcom = "set key at 0,0 top left")

should work.

**Comment by PetrKryslUCSD** [comment] 2018-05-03 16:59
I have taught `plot! ` to accept `gpcom` and to emit `llplot(gpcom)`. I do

```
set(terminal="pdf", outputfile = "Assembly CG" * ".pdf")
f = figure()
ns = coldata("Timing-hm" * ".csv", 1)
plot!(ns, coldata("Timing-hm" * ".csv", 2), legend = "ASSEMB HMATRIX", marker = "edmd", gpcom = "set key at 0,0 top left")
plot!(ns, coldata("Timing-am" * ".csv", 2), legend = "ASSEMB AMATRIX", marker = "fdmd", gpcom = "set key at 0,0 top left")
figure(f)
Gaston.gnuplot_send("set output")
```
but it has no effect whatsoever on the key location. Does it work for you?

**Comment by PetrKryslUCSD** [comment] 2018-05-03 17:38
This is my complete code:

```
using Gaston
using DelimitedFiles

function coldata(inputcsv, theset)
    contents = readdlm(inputcsv, ',', Float64, '\n'; header = true)
    return contents[1][:, theset]
end

set(axis="loglog", plotstyle="linespoints", linewidth=2, pointsize = 2, color = "black", xlabel = "Number of panels", ylabel = "Timing [s]", grid="on", title = "", xrange = "[1000:15000]")

set(terminal="pdf", outputfile = "Assembly CG" * ".pdf")
f = figure()
ns = coldata("Timing-hm" * ".csv", 1)
plot(ns, coldata("Timing-hm" * ".csv", 2), legend = "ASSEMB HMATRIX", marker = "edmd", gpcom = "set key at 0,0 top left")
plot!(ns, coldata("Timing-am" * ".csv", 2), legend = "ASSEMB AMATRIX", marker = "fdmd")
figure(f)
Gaston.gnuplot_send("set output")
sleep(3)
```
Unfortunately, even after the code update there is no change in the placement of the key.

**Comment by mbaz** [comment] 2018-05-03 22:54
OK, I needed to refresh my memory since I've been busy with other things for the past few weeks. The problem is that `gpcom` is not actually stored in the figure object, so your `plot!` command does not know about it.

This has been fixed, but in another branch I haven't pushed out. The branch has a lot of changes, mainly in order to make Gaston compatible with Jupyter's Interact package. There are a couple of things that I still need to fix in that branch before it's ready, though.

My schedule will be a bit better next week and I hope to make a new release in the next few days.

As a workaround, you can change Gaston's default legend placement in line 16 of `gaston_config.jl`. I'm sorry for the inconvenience!

**Comment by PetrKryslUCSD** [comment] 2018-05-04 01:06
Sounds good! Thank you very much for your help.

Petr Krysl
Professor
University of California, San Diego
9500 Gilman Dr., #0085, La Jolla, CA 92093
Skype: Petr.Krysl.UCSD.EDU
<https://mailtrack.io/trace/link/f495ad8887b180d5c0425e9e65e1ee5d672e19a3?url=http%3A%2F%2FPetr.Krysl.UCSD.EDU&userId=1197778&signature=fc0efe5da0fbe7a0>,
Office: 858-822-4787
http://hogwarts.ucsd.edu/~pkrysl/
<https://mailtrack.io/trace/link/0b96eaba11d56030e68fa153ed2b4e3d702f180e?url=http%3A%2F%2Fhogwarts.ucsd.edu%2F~pkrysl%2F&userId=1197778&signature=743472b5ebce6cf0>

**Comment by mbaz** [comment] 2018-05-07 16:18
Thanks for the info -- I'll take a look at this soon.

**Comment by mbaz** [comment] 2018-05-08 01:47
@PetrKryslUCSD Have you used the `box` plot option? It seems like it should do what you need:

    plot(1:10,legend="test",box="top left")

**Comment by PetrKryslUCSD** [comment] 2018-05-08 02:05
You are right, that works. But should it have? According to the manual, the "box" option should place a box around the key. It is not used to position the key.

**Comment by mbaz** [comment] 2018-05-08 02:19
What actually happens is that the entire `box` string is given to gnuplot prefixed with `set key`.

I need to document this option better....

**Comment by PetrKryslUCSD** [comment] 2018-05-08 02:27
Perhaps call it "keyoptions"?

**Comment by kim-tom** [comment] 2018-05-23 13:45
I fixed this way.
Ex.
plot(rand(10),rand(10), gpcom = "set key at 0,0 top left",legend="aiu")
↓
plot(rand(10),rand(10), box = "bottom right",legend="aiu")

**Comment by mbaz** [comment] 2019-04-29 16:31
Fixed in https://github.com/mbaz/Gaston.jl/commit/dafbcf8d9e0ea299b74b5fca5e6d053bfdacd44f

**Closed by mbaz** 2019-04-29 16:31 UTC
