### ISSUE TITLE
`imagesc` does not support setting the range

### ISSUE THREAD

**Issue by berceanu** [mbaz/Gaston.jl#29] opened 2014-06-24 10:09 UTC
Using "xrange" or "yrange" in `imagesc` results in an `Invalid property specified` error, while it seems to work fine for `surf`.

**Comment by mbaz** [comment] 2015-06-11 16:08
Duplicate of https://github.com/mbaz/Gaston.jl/issues/32

**Closed by mbaz** 2015-06-11 16:08 UTC
Labels: duplicate
