### ISSUE TITLE
No minor ticks grid in the tutorial (and code?)

### ISSUE THREAD

**Issue by sergstesh** [mbaz/Gaston.jl#108] opened 2019-04-08 15:58 UTC
Gaston does allow to (not) have grid displayed using "grid=<"on"_or_"off"> keyword argument in plot commands.

Gnuplot allows to also control grid linked to minor tics using e.g. the following command to enable grid linked to minor tics:

_set grid mxtics mytics_
.

I haven't found anything on grid linked to minor tics in the tutorial.

In practice adding

_gpcom="set grid mxtics mytics"_

to plot function enables grid linked to minor tics.

If the feature doesn't exist in code configuring grid display it would be nice to add it. In any case the documentation should mention the issue.

I have used the following code to test this:

_using Gaston
Gaston.gnuplot_send("set terminal qt noenhanced")
t = 0.001:0.001:1
plot(t,sin.(2π*5*t), title="A_sine_wave", xlabel="Time (s)", ylabel="Amplitude", axis="semilogx", grid="on", gpcom="set grid mxtics mytics")_
.

**Comment by sergstesh** [comment] 2019-04-08 16:02
And a related (?) issue.

'qt' terminal has a grid icon allowing to toggle grid display. When using the icon the grid is first turned off, and then turned on the part of grid linked to minor tics is not displayed.

**Comment by sergstesh** [comment] 2019-04-08 16:08
I think that enabling grid linked to minor tics should be the default. IIRC in very popular among electronic designers LTSpice there's no way to turn off grid linked to minor tics.

Line styles for grid lines linked to minor and major tics should probably be different though.

**Comment by mbaz** [comment] 2019-04-08 19:23
Indeed, I almost never use minor ticks so they've been a very low priority, especially since you can get them using `gpcom`. The best way to make this happen is to issue a pull request. Otherwise, I'll get to this after solving higher-priority issues.

I can reproduce the issue with the qt (and wxt, too) plot window, but that is a gnuplot bug. Their bug tracker is here: https://sourceforge.net/p/gnuplot/_list/tickets

**Comment by mbaz** [comment] 2019-06-18 19:17
Fixed in v0.10.0. See new docs: https://mbaz.github.io/Gaston.jl/v0.10.0/

**Closed by mbaz** 2019-06-18 19:17 UTC
Labels: enhancement
